// Code generated by hertz generator.

package consult

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consult0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
