// Code generated by hertz generator.

package admin

import (
	"CarBuyerAssitance/biz/dal/mysql"
	admin "CarBuyerAssitance/biz/model/admin"
	"CarBuyerAssitance/biz/pack"
	"CarBuyerAssitance/biz/service"
	"CarBuyerAssitance/pkg/errno"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
)

// AddUser .
// @router /api/admin/user/add [POST]
func AddUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AddUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(admin.AddUserResponse)
	userInfo, err := service.NewAdminService(ctx, c).AddUser(&mysql.User{
		Username:       req.Username,
		Password:       req.Password,
		Phone:          req.Phone,
		UserId:         req.UserId,
		BudgetMax:      req.BudgetMax,
		BudgetMin:      req.BudgetMin,
		PreferredType:  req.PreferredType,
		PreferredBrand: req.PreferredBrand,
		Status:         int8(req.Status),
		Address:        req.Address,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.UserID = userInfo
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// DeleteUser .
// @router /api/admin/user/delete [POST]
func DeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DeleteUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(admin.DeleteUserResponse)
	err = service.NewAdminService(ctx, c).DeleteUser(req.UserId)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryAllConsult .
// @router /api/admin/consult/query [POST]
func QueryAllConsult(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.QueryAllConsultRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(admin.QueryAllConsultResponse)
	info, total, err := service.NewAdminService(ctx, c).QueryAllConsult(int(req.PageNum), int(req.PageSize))
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.CList(info, total)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryA .
// @router /api/admin/query [GET]
func QueryA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.QueryARequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(admin.QueryAResponse)
	resp.Budget = pack.Budget()
	resp.Scene = pack.Scene()
	resp.Frequency = pack.Frequency()
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
