// Code generated by hertz generator.

package consult

import (
	"CarBuyerAssitance/biz/pack"
	"CarBuyerAssitance/biz/service"
	"CarBuyerAssitance/biz/service/model"
	"CarBuyerAssitance/pkg/errno"
	"context"

	consult "CarBuyerAssitance/biz/model/consult"
	"github.com/cloudwego/hertz/pkg/app"
)

// Consult .
// @router /api/consult/purchase [GET]
func Consult(ctx context.Context, c *app.RequestContext) {
	var err error
	var req consult.ConsultRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(consult.ConsultResponse)
	cd, err := service.NewConsultService(ctx, c).Consult(&model.Consult{
		BudgetRange:     req.BudgetRange,
		PreferredType:   req.PreferredType,
		UseCase:         req.UseCasecase,
		FuelType:        req.FuelType,
		BrandPreference: req.BrandPreference,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.ConsultResult(cd)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
