// Code generated by hertz generator.

package user

import (
	"CarBuyerAssitance/biz/dal/mysql"
	user "CarBuyerAssitance/biz/model/user"
	"CarBuyerAssitance/biz/mw/jwt"
	"CarBuyerAssitance/biz/pack"
	"CarBuyerAssitance/biz/service"
	"CarBuyerAssitance/pkg/errno"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
)

// Register .
// @router /api/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(user.RegisterResponse)
	userInfo, err := service.NewUserService(ctx, c).Register(&mysql.User{
		Username: req.Username,
		Password: req.Password,
		Phone:    req.PhoneNumber,
		UserId:   req.Id,
		Status:   1,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.UserID = userInfo
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// Login .
// @router /api/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.LoginResponse)
	userInfo, err := service.NewUserService(ctx, c).Login(req.Id, req.Password)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	jwt.AccessTokenJwtMiddleware.LoginHandler(ctx, c)
	jwt.RefreshTokenJwtMiddleware.LoginHandler(ctx, c)

	c.Header("Access-Token", c.GetString("Access-Token"))
	c.Header("Refresh-Token", c.GetString("Refresh-Token"))
	resp.Data = pack.User(userInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryUserInfo .
// @router /api/user/query/Info [GET]
func QueryUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.QueryUserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.QueryUserInfoResponse)
	userInfo, err := service.NewUserService(ctx, c).Query(req.UserID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.User(userInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UpdateUserInfo .
// @router /api/user/update/Info [GET]
func UpdateUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateUserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(user.UpdateUserInfoResponse)
	userInfo, err := service.NewUserService(ctx, c).Update(&mysql.User{
		BudgetMin:      req.BudgetMin,
		BudgetMax:      req.BudgetMax,
		Address:        req.Address,
		PreferredBrand: req.PreferredBrand,
		PreferredType:  req.PreferredType,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.User(userInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
