// Code generated by hertz generator.

package user

import (
	"CarBuyerAssitance/biz/dal/mysql"
	"CarBuyerAssitance/biz/pack"
	"CarBuyerAssitance/biz/service"
	"CarBuyerAssitance/pkg/errno"
	"context"

	user "CarBuyerAssitance/biz/model/user"
	"github.com/cloudwego/hertz/pkg/app"
)

// Register .
// @router /api/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(user.RegisterResponse)
	userInfo, err := service.NewUserService(ctx, c).Register(&mysql.User{
		Username: req.Username,
		Password: req.Password,
		Phone:    req.PhoneNumber,
		UserId:   req.Id,
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.UserID = userInfo
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// Login .
// @router /api/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(user.LoginResponse)
	userInfo, err := service.NewUserService(ctx, c).Login(req.Id, req.Password)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.User(userInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
