// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	consult "CarBuyerAssitance/biz/router/consult"
	model "CarBuyerAssitance/biz/router/model"
	user "CarBuyerAssitance/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	consult.Register(r)

	user.Register(r)

	model.Register(r)
}
